title: DC903 Defcoin Service Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: http://defcoin.dc903.org
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: defcoind - 1337
      description: defcoind node
      category: defcoin.dc903.org
    - name: p2pool - 13372
      description: Mining pool
      category: defcoin.dc903.org
    - name: Pool Web UI
      description: Web UI showing stats of pool, miners, recent blocks, and more
      category: defcoin.dc903.org
    - name: Explorer Web UI
      description: Web UI serving a Defcoin block explorer
      category: explorer.dc903.org
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: dc903_defcoin_logo.jpeg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: defcoin.dc903.org
      description: The DC903 Defcoin pool
    - name: explorer.dc903.org
      description: The DC903 Defcoin block explorer
  description: DC903 Defcoin server status page
  enableCustomHTML: true
  useLargeHeaderDesign: true
